name: 'Build site'

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ''

      upload:
        type: boolean
        default: false
        required: false

jobs:
  build:
    name: 'Create build'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - run: yarn translations:import

      - name: 'Handle build cache'
        id: cache-build
        uses: actions/cache@v3
        with:
          path: src/.vuepress/dist
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.lock') }}-${{ hashFiles('src/**/*') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/*.lock') }}
            ${{ runner.os }}-build

      - uses: myparcelnl/actions/yarn2-install@v2
        if: steps.cache-build.outputs.cache-hit != 'true'

      - run: yarn build
        if: steps.cache-build.outputs.cache-hit != 'true'

      - uses: actions/upload-artifact@v3
        if: inputs.upload != 'false'
        with:
          name: build
          path: src/.vuepress/dist
