navbar:
  - text: API Reference
    link: /api-reference/
  - text: Documentatie
    link: /nl/documentatie/
  - text: Integraties
    link: /nl/integraties.html
  - text: Over ons
    link: /about.html
  - text: Contact
    link: /contact.html
  - text: Status
    link: 'https://status.myparcel.nl/'

footer:
  - text: Documentatie
    link: /nl/documentatie/
    children:
      - text: Aan de slag
        link: /getting-started.html
      - text: WooCommerce
        link: /nl/documentatie/10.woocommerce.html
      - text: Prestashop
        link: /nl/documentatie/11.prestashop.html
      - text: Magento2
        link: /nl/documentatie/13.magento2.html
      - text: Shopify
        link: /nl/documentatie/14.shopify.html
      - text: Shopware
        link: /nl/documentatie/15.shopware.html
      - text: Lightspeed
        link: /nl/documentatie/16.lightspeed.html
      - text: Ecwid
        link: /nl/documentatie/17.ecwid.html
      - text: Bol.
        link: /nl/documentatie/18.bol.html
      - text: Wix
        link: /nl/documentatie/20.wix.html
      - text: Amazon
        link: /nl/documentatie/25.amazon.html
      - text: Etsy
        link: /nl/documentatie/30.etsy.html
      - text: Chrome extension
        link: /nl/documentatie/40.chrome-extension.html
      - text: PHP SDK
        link: /documentation/50.php-sdk.html
      - text: JS SDK
        link: /documentation/51.javascript-sdk.html
      - text: Delivery Options
        link: /documentation/60.delivery-options.html

  - text: API Reference (EN)
    children:
      - text: Intro
        link: /api-reference/
      - text: Data Types
        link: /api-reference/04.data-types.html
      - text: Authentication
        link: /api-reference/05.authentication.html
      - text: Shipments
        link: /api-reference/06.shipments.html
      - text: Delivery options
        link: /api-reference/08.delivery-options.html
      - text: Webhooks
        link: /api-reference/10.webhooks.html

  - text: Contact
    children:
      - text: Neem contact met ons op
        link: /contact.html
      - text: Chat met ons op Slack
        link: https://join.slack.com/t/myparcel-dev/shared_invite/zt-2zvk9gfs1-h6koDUduK6ZM_kZcc247AQ
      - text: Word partner
        link: 'https://www.myparcel.nl/partner-worden/'

  - text: ''
    children:
      - text: Status
        link: 'https://status.myparcel.nl/'
      - text: Over ons
        link: /about.html
      - text: Vacatures
        link: 'https://www.myparcel.nl/vacature/development/'
      - text: GitHub
        link: 'https://github.com/myparcelnl/'
      - text: MyParcel
        link: 'https://www.myparcel.nl/'
      - text: SendMyParcel
        link: 'https://www.sendmyparcel.be/'

footer2:
  - text: Voorwaarden & beleid
    link: >-
      https://backoffice.myparcel.nl/static/myparcel-nederland/documentatie/voorwaarden/myparcel-algemene-voorwaarden.pdf
  - text: Cookiestatement
    link: >-
      https://backoffice.myparcel.nl/static/myparcel-nederland/documentatie/voorwaarden/myparcel-cookie-statement.pdf
  - text: Privacyverklaring
    link: >-
      https://backoffice.myparcel.nl/static/myparcel-nederland/documentatie/voorwaarden/myparcel-privacy-statement.pdf
